### PR TITLE
Allow inverting laziness of files.

### PR DESCRIPTION
**Pull request by jsirois**
Using `--invert-lazy <file id>` to flip the lazy bit on a file allows
use of a single lift manifest to produce both skinny scies and fat
binaries.

A `--name` option to re-name the binary is also added to make the
use-case a one-stop operation.

### CODE REVIEW

**Comment by jsirois** [comment]
This builds on top of #12 starting with he 4th commit: 1b98747

**Comment by jsirois** [comment]
I'm going to submit after submitting #12 as soon as #14 goes green to unwind the stack from here to there.

**Review by benjyw — COMMENTED** [review]
I guess the alternative would be to introduce inheritance/overrides or includes in manifests, and that seems like massive overkill, so this seems like good, if quirky, way of achieving the purpose.

**Comment by jsirois** [comment]
> I guess the alternative would be to introduce inheritance/overrides or includes in manifests, and that seems like massive overkill

Exactly. Any that can always be added later or externally with a templating tool like CUE that is purpose built for this sort of thing. I like composing tools instead of trying to do everything where possible.

**Pull request merged**
